### ISSUE TITLE
Server side também disponível ?

### ISSUE THREAD

**Issue by mrgiba** [leitordenotas/leitordenotas.github.io#2]
O código fonte do lado server da aplicação também está disponível ?

https://github.com/leitordenotas/leitordenotas.github.io/blob/71ce96e2321e09c73c1d847622bdd9cb105461d7/functions.js#L32-L33

**Comment by cvscarlos** [comment]
Olá, o backend não esta disponível!

**Comment by renerlemes** [comment]
É possível negociar uma venda do código do back-end ou a forma como é feito?

**Comment by cvscarlos** [comment]
@renerlemes falo contigo no PV.

**Comment by lucianojsjr** [comment]
@caljp13 podes me mandar uma mensagem PV?

**Comment by andrempo** [comment]
Inútil deixar o código publico no github dessa forma. Perdi meu tempo tentando entender o projeto.
